### ISSUE TITLE
Add Aprilaire Programming Guide? 

### ISSUE THREAD

**Issue by ADeadPixel** [chamberlain2007/aprilaire-ha#1]
Can you add the programming guide to this repo or is the guide to big for that? Aprilaire hasn't replied to any of my emails so I don't have it.

**Comment by chamberlain2007** [comment]
Unfortunately since it is Aprilaire's IP, I can't include it in the repo due to licensing. If you shoot me a DM on https://community.home-assistant.io/ I can send you a copy. I got it from them very easily via their contact form at https://www.aprilaire.com/contact, where I requested the Wifi Programmer Guide and received it in under 24 hours.
