### ISSUE TITLE
Possible issue in coordinator

### ISSUE THREAD

**Issue by BrianHumlicek** [chamberlain2007/aprilaire-ha#29]
In coordinator.py, line 97 is currently

await self.client.wait_for_response(FunctionalDomain.IDENTIFICATION, 4, 30)

I believe the 4 should be a 5, and I think that is why I am seeing "Received NACK for attribute 7" in my logs.

In the logs, the sent data appears to be correct (attribute is 5 and not 4), and I'm not sure why, so, double check everything I am saying here.

Brian

**Comment by BrianHumlicek** [comment]
I tried changing it and now I am seeing "Hit timeout of 30 waiting for 8, 5", so, I think there is something that I am not understanding about the above code.

**Comment by chamberlain2007** [comment]
@BrianHumlicek So the documentation is really bad on this particular attribute. It says in the documentation that it is 4, but what I've seen in practice is that when you read it you need to send 5 and it comes back with 4. No idea why, but that's why it's like that. There shouldn't be any ill effect to it.

Regarding the NACK, that means at some point there is an unknown attribute. It's hard to track down because there is nothing in the NACK that actually specifies what attribute was unknown. I haven't seen any issues because of it so I don't think it's worth spending the time going one by one through every call to try to find it.
