### ISSUE TITLE
8840 - Fresh Air Ventilator and Fan Controls are only Sensors not Switches

### ISSUE THREAD

**Issue by JDNEU** [chamberlain2007/aprilaire-ha#38]
Hi, I used this integration with 8840 Aprilaire thermostat. The documentation mentions about the ability to "Trigger and cancel air cleaning and fresh air events". Though the thermostat supports Fan and Fresh Air Ventilator control, integration did not create any switches for it, it created only sensors. How to trigger  Fan and Fresh Air Events?

![image](https://github.com/chamberlain2007/aprilaire-ha/assets/117293241/bc02dec1-9d19-4284-befd-1d71a85a245d)

**Comment by JDNEU** [comment]
Ah Great, Thank you for your Help :-). Btw, the python thermostat emulator is super awesome. Thanks

**Comment by chamberlain2007** [comment]
Great!

Yes the mock server is really helpful, testing the code against a physical device is a pain because it can only have one connection at a time. My workflow is normally to do the development against the mock server, then do an integration test against my physical device once it's at the release stage.
